yarnPath: .yarn/releases/yarn-4.10.3.cjs

nodeLinker: node-modules

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistries:
  //registry.npmjs.org:
    npmAlwaysAuth: false
    npmAuthToken: "${NPM_TOKEN}"

npmRegistryServer: "https://registry.npmjs.org"

npmPublishAccess: public
