yarnPath: .yarn/releases/yarn-4.6.0.cjs

nodeLinker: node-modules

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistries:
  //registry.npmjs.org:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"

npmRegistryServer: "https://registry.npmjs.org"

npmPublishAccess: public
