name: "Run main workflow"

on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Generate bot app token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.ACTIONS_BOT_ID }}
          private-key: ${{ secrets.ACTIONS_BOT_KEY }}
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - name: Set up Node 22
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: yarn install
      - name: Run build
        run: yarn build
      - name: Run tests
        run: yarn test
      - name: Run release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: yarn semantic-release
