name: "Run PR workflow"

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Node 22
        uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: yarn install
      - name: Run lint
        run: yarn lint
      - name: Run build
        run: yarn build
      - name: Run tests
        run: yarn test
      - name: Run release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: yarn semantic-release --dry-run
